/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"

#include "bar_alpha.h"
#include "combo.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_systray.h"

/* Other patches */
#include "cfacts.h"
#include "cool_autostart.h"
#include "cyclelayouts.h"
#include "decorationhints.h"
#include "dragcfact.h"
#include "fullscreen.h"
#include "inplacerotate.h"
#include "moveresize.h"
#include "pertag.h"
#include "reorganizetags.h"
#include "scratchpad.h"
#include "setborderpx.h"
#include "shiftviewclients.h"
#include "stacker.h"
#include "sticky.h"
#include "swallow.h"
#include "swaptags.h"
#include "tagall.h"
#include "tagswapmon.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_flextile-deluxe.h"
#include "layout_gapplessgrid.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_monocle.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"
